import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { NoorButton, ParentShell } from "@/components/noor";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { clearState, loadState, saveState } from "@/lib/noor-store";
import type { ChildProfile } from "@/types/noor";
export const Route=createFileRoute("/parent/settings")({head:()=>({meta:[{title:"إعدادات الطفل | نور"},{name:"description",content:"خصص مدة الجلسة والاستماع ووضع التركيز."},{property:"og:title",content:"إعدادات الطفل | نور"},{property:"og:description",content:"خصص مدة الجلسة والاستماع ووضع التركيز."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:SettingsPage});
function SettingsPage(){const navigate=useNavigate();const [child,setChild]=useState<ChildProfile>();const [saved,setSaved]=useState(false);useEffect(()=>setChild(loadState().child),[]);if(!child)return null;const commit=()=>{const state=loadState();state.child=child;saveState(state);setSaved(true);window.setTimeout(()=>setSaved(false),1600)};return <ParentShell><main className="mx-auto max-w-2xl px-5 py-10"><h1 className="text-3xl font-bold">إعدادات الطفل</h1><div className="mt-8 space-y-5"><section className="rounded-[20px] border border-border p-5 shadow-soft"><label className="text-sm text-muted-foreground">الاسم</label><input value={child.name} onChange={e=>setChild({...child,name:e.target.value})} className="mt-2 min-h-12 w-full rounded-xl border border-input px-4 text-lg outline-none focus:ring-2 focus:ring-ring"/><label className="mt-5 block text-sm text-muted-foreground">العمر</label><select value={child.age} onChange={e=>setChild({...child,age:Number(e.target.value)})} className="mt-2 min-h-12 w-full rounded-xl border border-input bg-background px-4">{[3,4,5,6,7,8,9,10,11,12].map(n=><option key={n}>{n} سنوات</option>)}</select></section><section className="rounded-[20px] border border-border p-5 shadow-soft"><Setting label="وضع التركيز" detail="جلسات أقصر ونشاط أكثر"><Switch dir="ltr" checked={child.focusMode} onCheckedChange={v=>setChild({...child,focusMode:v})}/></Setting><Setting label="الصوت" detail="تشغيل الاستماع والتشجيع"><Switch dir="ltr" checked={child.sound} onCheckedChange={v=>setChild({...child,sound:v})}/></Setting><div className="mt-6"><p className="font-bold">مدة الجلسة</p><div className="mt-3 grid grid-cols-3 gap-2">{([3,5,8] as const).map(n=><Button key={n} variant={child.sessionLength===n?"default":"secondary"} onClick={()=>setChild({...child,sessionLength:n})} className="min-h-11 rounded-xl">{n} دقائق</Button>)}</div></div><div className="mt-6"><div className="flex justify-between"><p className="font-bold">سرعة الاستماع</p><span className="text-sm text-muted-foreground">{child.speechRate.toFixed(1)}×</span></div><Slider dir="ltr" min={.6} max={1.2} step={.1} value={[child.speechRate]} onValueChange={v=>setChild({...child,speechRate:v[0]??.85})} className="mt-5"/></div></section><div className="flex items-start gap-3 rounded-[20px] bg-child p-5"><ShieldCheck className="mt-1 shrink-0 text-primary"/><p className="text-sm leading-7">لا نطلب تشخيصًا طبيًا، ولا نخزّن أي بيانات حساسة. نحفظ فقط الاسم والعمر والتقدم على هذا الجهاز.</p></div><NoorButton className="w-full" onClick={commit}>{saved?"تم الحفظ":"حفظ الإعدادات"}</NoorButton><Button variant="ghost" className="min-h-12 w-full text-muted-foreground" onClick={()=>{if(window.confirm("هل تريد حذف بيانات الطفل من هذا الجهاز؟")){clearState();void navigate({to:"/"})}}}><Trash2/> حذف بيانات الطفل</Button></div></main></ParentShell>}
function Setting({label,detail,children}:{label:string;detail:string;children:ReactNode}){return <div className="flex items-center justify-between gap-5 border-b border-border py-4 first:pt-0"><div><p className="font-bold">{label}</p><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div>{children}</div>}