/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as ParentAnswerIdRouteImport } from './routes/parent.answer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentAnswerIdRoute = ParentAnswerIdRouteImport.update({
  id: '/answer/$id',
  path: '/answer/$id',
  getParentRoute: () => ParentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/parent': typeof ParentRouteWithChildren
  '/processing': typeof ProcessingRoute
  '/referral': typeof ReferralRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/session/$id': typeof SessionIdRoute
  '/parent/': typeof ParentIndexRoute
  '/parent/answer/$id': typeof ParentAnswerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/processing': typeof ProcessingRoute
  '/referral': typeof ReferralRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/session/$id': typeof SessionIdRoute
  '/parent': typeof ParentIndexRoute
  '/parent/answer/$id': typeof ParentAnswerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/parent': typeof ParentRouteWithChildren
  '/processing': typeof ProcessingRoute
  '/referral': typeof ReferralRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/session/$id': typeof SessionIdRoute
  '/parent/': typeof ParentIndexRoute
  '/parent/answer/$id': typeof ParentAnswerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/parent'
    | '/processing'
    | '/referral'
    | '/parent/settings'
    | '/session/$id'
    | '/parent/'
    | '/parent/answer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/processing'
    | '/referral'
    | '/parent/settings'
    | '/session/$id'
    | '/parent'
    | '/parent/answer/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/parent'
    | '/processing'
    | '/referral'
    | '/parent/settings'
    | '/session/$id'
    | '/parent/'
    | '/parent/answer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ParentRoute: typeof ParentRouteWithChildren
  ProcessingRoute: typeof ProcessingRoute
  ReferralRoute: typeof ReferralRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/answer/$id': {
      id: '/parent/answer/$id'
      path: '/answer/$id'
      fullPath: '/parent/answer/$id'
      preLoaderRoute: typeof ParentAnswerIdRouteImport
      parentRoute: typeof ParentRoute
    }
  }
}

interface ParentRouteChildren {
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentIndexRoute: typeof ParentIndexRoute
  ParentAnswerIdRoute: typeof ParentAnswerIdRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentSettingsRoute: ParentSettingsRoute,
  ParentIndexRoute: ParentIndexRoute,
  ParentAnswerIdRoute: ParentAnswerIdRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ParentRoute: ParentRouteWithChildren,
  ProcessingRoute: ProcessingRoute,
  ReferralRoute: ReferralRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
